### ISSUE TITLE
Question - setting an image after creation

### ISSUE THREAD

**Issue by hawkeye64** [zhanziyang/vue-croppa#1]
After using the <img> tag to set an initial image, how do you change it? Say, the User did some action on a form which then required a different image to be displayed?

**Comment by zhanziyang** [comment]
You can use the `refresh()` method after changing the image. Here is an example: https://jsfiddle.net/yfu1cows/2/

Make sure you update to the latest version (0.0.18) because I have done some optimizations.

**Comment by hawkeye64** [comment]
Thank you so much! This worked as expected!

**Comment by zhanziyang** [comment]
You are welcome! I'm glad it works.
