### ISSUE TITLE
如何获取裁剪之后的图片file

### ISSUE THREAD

**Issue by thorliyang** [zhanziyang/vue-croppa#10]

**Comment by zhanziyang** [comment]
> file 是一种特殊的 blob

可以用 `generateBlob`([#](https://github.com/zhanziyang/vue-croppa#mycroppagenerateblob-callback-function-mimetype-string-qualityargument-number-)) 或 `promisedBlob`([#](https://github.com/zhanziyang/vue-croppa#mycroppapromisedblob-mimetype-string-qualityargument-number-)) 方法获取到文件blob，从而进行上传或者下载。

建议你看看这些文章：
https://developer.mozilla.org/zh-CN/docs/Web/API/Blob
http://javascript.ruanyifeng.com/htmlapi/file.html

**Comment by zhanziyang** [comment]
https://zhanziyang.github.io/vue-croppa/#/file-output
