### ISSUE TITLE
Tainted canvases may not be exported

### ISSUE THREAD

**Issue by pdipasqua** [zhanziyang/vue-croppa#102]
Hi guys,
I found this issue with nuxt when call the generateBlob function.
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by zhanziyang** [comment]
Please see #12 #63

**Comment by zhanziyang** [comment]
@Sergio-Abreu You should use `new-image-drawn` event instead of `new-image`. I believe that will solve your problem : )

**Comment by zhanziyang** [comment]
@pdipasqua Does these #12 #63 help?

**Comment by Sergio-Abreu** [comment]
@zhanziyang I have tried this too

**Comment by thejams** [comment]
Does anyone have figure how to resolve this issue? I have tried this too #12 #63

**Comment by Sergio-Abreu** [comment]
this was my workaround
```
mounted () {
    this.$http.get(this.picture, {responseType: 'blob'}).then(
        (result) => {
            this.croppa._onNewFileIn(result.body);
        }, 
        (error) => { console.log(error) }
    );
}
```

picture is the url to the image, now must have find a way to have img type and name from the url

**Comment by pdipasqua** [comment]
@zhanziyang Hi, I have tried this too #12 #63 but doesn't work!

this is my code:

`           <croppa v-model="avatar"
            :width="250"
            :height="250"
            placeholder="Scegli un'immagine"
            :placeholder-font-size="14"
            :prevent-white-space="true"
            :show-remove-button="true"
            remove-button-color="black"
            :remove-button-size="35"
            :quality="1"
            @image-remove="modelUser.newAvatar = true"
            @file-choose="modelUser.newAvatar = true"
            :disable-scroll-to-zoom="avatar.currentIsInitial">  
          <img v-if="modelUser.avatar_url"
              :src="modelUser.avatar_url"
              slot="initial">
          </croppa >`


` storeUser(newUser) {
        newUser.blob=null
        if (this.avatar.hasImage()) {
              this.avatar.generateBlob((blob) => {
                newUser.blob = blob
                this.$store.dispatch('users/storeUser', newUser)
              }, 'image/jpeg', 0.8) // 80% compressed jpeg file
        } else {
             this.$store.dispatch('users/storeUser', newUser)
        }
  }`

**Comment by zhanziyang** [comment]
@pdipasqua Have you tried this?
`<img v-if="modelUser.avatar_url" crossOrigin="anonymous" :src="modelUser.avatar_url" slot="initial">`

The important part is the `crossOrigin="anonymous"` and it should be written before `src`

**Comment by pdipasqua** [comment]
crossOrigin="anonymous" solved my issue. Many Thanks

**Comment by yagoml** [comment]
crossOrigin="anonymous" solve to send file, but give me a CORS error when i try set **initial-image**.

**Comment by yiyasha15** [comment]
> crossOrigin="anonymous" solve to send file, but give me a CORS error when i try set **initial-image**.

did anyone find any solution to this?
