### ISSUE TITLE
Getting metada

### ISSUE THREAD

**Issue by Yarisrespect** [zhanziyang/vue-croppa#103]
Hi, is it possible to get metadata from any event?
It would be nice to add some "change" event...

**Comment by zhanziyang** [comment]
Maybe you can use "draw" event. It always fires when metadata changes.

**Comment by Yarisrespect** [comment]
No, I mean to get that data while you drawing but do not call method "getMetadata" while drawing.

**Comment by zhanziyang** [comment]
I see. It's possible. will try to implement this soon.

**Comment by zhanziyang** [comment]
Sorry, after reconsidering I don't think it's necessary to do this. Just call `getMetadata()`.
