### ISSUE TITLE
Wrong margin or padding in croppa element?

### ISSUE THREAD

**Issue by Jaszkowic** [zhanziyang/vue-croppa#110]
I am wondering why there is additional transparent space right below the `croppa` element (see attached image). Is there some kind of margin / padding applied to the element? Can I turn it off somehow?

HTML: 

```
<div id="app">
  <div style="background-color: green">
    <croppa v-model="myCroppa" :width="400" :height="400" style="background-color: red"></croppa>
  </div>
</div>
```

CSS:

```
.croppa-container {
  background-color: lightblue;
  border: 1px solid black;
}
```

It is kind of interfering when trying to align divs.

![CroppaDemo](https://user-images.githubusercontent.com/10830180/40236289-572c4b44-5aad-11e8-8a65-775f6a7ddb8b.png)

**Comment by zhanziyang** [comment]
try setting it to block element. It's inline-block by default.
```css
.croppa-container {
  display: block;
}
```
