### ISSUE TITLE
initial-size "contain" does not work with <img> slot

### ISSUE THREAD

**Issue by pmochine** [zhanziyang/vue-croppa#111]
So try this out:

https://codepen.io/shadrix/pen/JvVOGx

Load a File and you will see it's zoomed in.

**Comment by pmochine** [comment]
Okay I see the problem right now. It's the same for this: https://codepen.io/shadrix/pen/rvbYEb

The problem is that croppa is not removing the initial picture when selecting a new one. That is why it gets zoomed in.

**Comment by zhanziyang** [comment]
Bug fixed in new version 1.3.7. Please upgrade : )
