### ISSUE TITLE
Cross Origin Error

### ISSUE THREAD

**Issue by seedgabo** [zhanziyang/vue-croppa#12]
trying to access to a image in a different server gets

Access to Image at from origin 'http://localhost:4500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4500' is therefore not allowed access.

**Comment by zhanziyang** [comment]
1. Make sure the server response of the image you request has the header `Access-Control-Allow-Origin` set to `*`, otherwise it means the resource can not be accessed from other domains (basically it means "you can't use my images on your site").

2. If `Access-Control-Allow-Origin` is set to `*`, make sure you use the [`initial-image` prop](https://github.com/zhanziyang/vue-croppa#initial-image) instead of `initial` slot to apply an image url.

**Comment by seedgabo** [comment]
Great thanks!

**Comment by nielslucas** [comment]
@zhanziyang Hi, I still got that issue for loading the image. This is how my code works: 
```
<div :class="input_class">
	<croppa v-model="img"
		...
		:initial-image="preview" <!-- does not show my image and got CORS error -->
	></croppa>
	</div>
	<img :src="preview"> <!-- does show image -->
</div>
```
Am I doing something wrong here?

**Comment by lupas** [comment]
> @zhanziyang Hi, I still got that issue for loading the image. This is how my code works:
> 
> ```
> <div :class="input_class">
> 	<croppa v-model="img"
> 		...
> 		:initial-image="preview" 
> 	></croppa>
> 	</div>
> 	<img :src="preview"> 
> </div>
> ```
> Am I doing something wrong here?

Try this:
```html
<croppa v-model="img"
	...
>
<img slot="initial" :src="preview" />
</croppa>
```

Make sure to delete `:initial-image="preview"`

Should get rid of the cors error.

**Comment by yiyasha15** [comment]
> > @zhanziyang Hi, I still got that issue for loading the image. This is how my code works:
> > ```
> > <div :class="input_class">
> > 	<croppa v-model="img"
> > 		...
> > 		:initial-image="preview" 
> > 	></croppa>
> > 	</div>
> > 	<img :src="preview"> 
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I doing something wrong here?
> 
> Try this:
> 
> ```
> <croppa v-model="img"
> 	...
> >
> <img slot="initial" :src="preview" />
> </croppa>
> ```
> 
> Make sure to delete `:initial-image="preview"`
> 
> Should get rid of the cors error.

This worked!! Thanks a ton.
