### ISSUE TITLE
Issue in Facebook In-App browser using vue-croppa.

### ISSUE THREAD

**Issue by probir17** [zhanziyang/vue-croppa#120]
Redirecting from facebook app to Facebook In-App browser,while choosing image from camera(gallery),it seems all the images are disabled.No images can be selected.
Any idea to solve it?

Thanks in advance.

**Comment by zhanziyang** [comment]
Please try setting the `accept` prop implicitly. For example:
```html
<croppa :accept="'image/*'"></croppa>
```

**Comment by probir17** [comment]
Thank you so much Sir.
Its working totally fine.
And also sorry for late reply.. :relaxed:

**Comment by zhanziyang** [comment]
Glad it works : ) I'm closing this then.
