### ISSUE TITLE
你好，我想你这个能不能帮我压缩图片 因为现在手机拍照的大小实在是太大了

### ISSUE THREAD

**Issue by yehoan** [zhanziyang/vue-croppa#121]

**Comment by zhanziyang** [comment]
可以。请在文档中搜索“ compressionRate” 关键字相关的用法

**Comment by yehoan** [comment]
这样我的说下我的需求环境吧 就是我现在用这个compressionRate 可以把一个 图片压缩成一些比例  然后我得到的是一个base64的编码的图片然后我发现后台他要求他这个Base64的转成new Formate 的文件流  不知道有提供方法没有 谢谢 我试了 好像可以 有个例子 就是上传的是那个blob 参数然后可以那到这个对象 但是我 要做的事即使聊天的就是用户一选择图片调取那个原生的api 就立刻就能难道那个Bolb 不是通过按钮触发 我试了直接给我null

**Comment by zhanziyang** [comment]
这位同学，你的发言没有标点而且好多错别字看得我好累😫。。。
> 我 要做的事即使聊天的就是用户一选择图片调取那个原生的api  就立刻就能难道那个Bolb

你说的选择图片的原生API也是通过某些事件触发的吧？把你原本触发的方式改为调用`croppa.chooseFile()`方法就好了。
