### ISSUE TITLE
new-image-drawn event not fired when image added with chooseFile() method

### ISSUE THREAD

**Issue by rwfresh** [zhanziyang/vue-croppa#124]
When adding a new image to a croppa instance using the chooseFile() method the new-image-drawn event is not fired.

https://codepen.io/anon/pen/zLYQVz

Not necessarily a bug as you can force hasImage() to false by using remove() before the new image is selected which will result in the event being emitted. 

In my case I'd like to replace the existing image and still have the event fired so that the new image will be sized correctly according to my initial-size prop value

**Comment by zhanziyang** [comment]
I tried the demo and the event is fired. I record the screen:

https://www.useloom.com/share/d88cec876178418a8647adbcca24c108

**Comment by rwfresh** [comment]
Load one and then use the chooseFile() to load another. Only fires on the first load.

My use case is a profile image. The user may already have a profile image and may choose to edit the existing image OR replace it with a new one. In this case I pass an initial image prop and so I must display a button with chooseFile(). Since an initial image is loaded on init adding a replacement image does not fire the new-image-drawn event. Try for yourself with the same codepen.

The work around is to remove() the initial image before the second one is added. The problem here is if the user cancels the file input there is no way to capture that event and replace the initial image.

**Comment by zhanziyang** [comment]
@rwfresh Indeed. Will fix the bug. Please use `remove()` for now.

**Comment by rwfresh** [comment]
@zhanziyang Thank you very much for making this component. I really appreciate it. I went through the code to see if I could modify and make a pull request but I haven't had enough time to actually track it down.

**Comment by rwfresh** [comment]
Also, might be of value for other users, I have a demo where I place an overlay that helps end users frame their image much like linkedIn's profile image editor. This fix will make it run much smoother. I will create a codepen demo.

**Comment by zhanziyang** [comment]
@rwfresh  Sounds awesome!

**Comment by zhanziyang** [comment]
@rwfresh  Bug fixed in new version 1.3.7. Please upgrade : )

**Comment by rwfresh** [comment]
Hi @zhanziyang Thanks for this fix. Finally had a chance to review my code. Here's a codepen with the overlay I was talking about. https://codepen.io/rwfresh/pen/zLYQVz

**Comment by zhanziyang** [comment]
Thanks @rwfresh. That's a cool demo. Maybe later I will add it to the [demo page](https://zhanziyang.github.io/vue-croppa/#/demos).

**Comment by rwfresh** [comment]
@zhanziyang right on. Again, thanks to you for taking the time to put this together.

**Comment by spham** [comment]
@zhanziyang , it seems not update in demo.
