### ISSUE TITLE
不能做移动端自适应吗？

### ISSUE THREAD

**Issue by youlong723687543** [zhanziyang/vue-croppa#128]
请问下，不能做移动端自适应吗？

**Comment by zhanziyang** [comment]
用 `auto-sizing` 结合 css，相关issue: #76 里面有个demo

**Comment by youlong723687543** [comment]
谢谢您的及时回复，还有个问题，就是这个组件有onchange事件吗？我现在需要判断组件是否有图片，然后让页面加载

在 2018-08-02 13:27:28，"Chris Zhan" <notifications@github.com> 写道：


用 auto-sizing 结合 css，相关issue: #76 里面有个demo

**Comment by zhanziyang** [comment]
有`new-image-drawn`和`remove`应该可以满足您的需求

**Comment by youlong723687543** [comment]
好的，谢谢，我明白了

在 2018-08-02 13:49:50，"Chris Zhan" <notifications@github.com> 写道：


有new-image-drawn和remove应该可以满足您的需求
