### ISSUE TITLE
Crop Avatar Image in Perfect Circle...

### ISSUE THREAD

**Issue by rubencool** [zhanziyang/vue-croppa#132]
I was trying to crop image in perfect circle like avatar image. but it was not a perfect circle. so how can i get perfect avatar circle. Your library doesn`t support, perfect circle. Is there is any keyword to cut in perfect circle. i had tried before, Here is my code please suggested me.

  ![code screen shot](https://user-images.githubusercontent.com/14999212/43858561-16cf4a86-9b6e-11e8-8eb1-20cfb8d10dca.png)

![issueimage](https://user-images.githubusercontent.com/14999212/43858376-98dceb4c-9b6d-11e8-8d8d-b8fd5a37e0c4.jpg)

**Comment by zhanziyang** [comment]
Actually you can use the "clip plugin" feature with a little bit knowledge of Canvas API. See demo below:
https://codepen.io/zhanziyang/pen/GQKmJq
