### ISSUE TITLE
Copy images to other croppa components?

### ISSUE THREAD

**Issue by DerekVance** [zhanziyang/vue-croppa#133]
Thank you for taking the time to make this! Is it possible to have 2 croppa components and when an image is put into one component copy it to another croppa component. I would like to have the user crop the same image at 2 different aspect ratios. 

Thank you.

**Comment by zhanziyang** [comment]
Using `_onload` can easily achieve this. See the demo below:
https://codepen.io/zhanziyang/pen/YjbLLX?editors=1010

**Comment by DerekVance** [comment]
Excellent! Thank you!
