### ISSUE TITLE
可以支持透明图片吗？

### ISSUE THREAD

**Issue by qq27375** [zhanziyang/vue-croppa#137]
黑色图标、透明背景，上传上去以后直接变成一坨黑了。

**Comment by qq27375** [comment]
我用你提供的透明图片https://vignette.wikia.nocookie.net/zelda/images/9/9b/Link_Gauntlets_%28Hyrule_Warriors%29.png/revision/latest?cb=20140810231906
上传上去以后，背景色就变成黑色了。

画布可以设置背景色为透明色，但上传结果就是黑色。
你提供的demo看不到上传结果。

我本地的测试图片：http://sjfx.1314179.com.cn/test.png

**Comment by qq27375** [comment]
找到原因了。取blob数据时，传的参数修改一下就可以了。
```
        this.myCroppa.generateBlob((blob) => {
        }, 'image/jpeg', this.ratio)
``````
        this.myCroppa.generateBlob((blob) => {
        }, 'image/png', this.ratio)
```

**Comment by peewee922** [comment]
this.ratio应该设为多少呢？我试了几个值还是一坨黑

> 找到原因了。取blob数据时，传的参数修改一下就可以了。
> 
> ```
>         this.myCroppa.generateBlob((blob) => {
>         }, 'image/jpeg', this.ratio)
> ```
> ```
>     this.myCroppa.generateBlob((blob) => {
>     }, 'image/png', this.ratio)
> ```

 this.ratio应该设为多少呢？我试了几个值还是一坨黑

**Comment by qq27375** [comment]
> this.ratio应该设为多少呢？我试了几个值还是一坨黑
jpeg图片的图片质量，取值是0-1之间，一般是0.6或者0.8，数值越大，越清晰，文件也越大

**Comment by zhanziyang** [comment]
@w19871029 拿到的 file 跟 blob 用法是一样的。除了file-choose事件，还可以用`croppa.getChosenFile()`取得
