### ISSUE TITLE
Does not load images on iPads (iOS 10.2.1)

### ISSUE THREAD

**Issue by green-coder** [zhanziyang/vue-croppa#14]
The problem happens on both Safari and Google Chrome.

The initial image gets displayed however.

**Comment by zhanziyang** [comment]
Are there any error messages or warnings in the console?

**Comment by green-coder** [comment]
On the iPad with Safari, it shows this error after taking a photo :

> Cross-origin image load denied by Cross-Origin Resource Sharing policy.

**Comment by zhanziyang** [comment]
How do you apply initial image? If you use images from another domain, please use `initial-image` prop instead of using slot.

See more in #12

**Comment by green-coder** [comment]
When I am browsing your demo page, I use the button 'Choose File', the picture comes directly from the camera. Same problem when I select it from the iPad's picture library.

**Comment by zhanziyang** [comment]
Sorry I don't have an iPad so I can't test it at the moment.

Please try this demo and see if the error still occurs.
https://jsfiddle.net/jdcvpvty/6/

**Comment by green-coder** [comment]
For a reason which I don't understand, it now works when choosing the files from the picture library. It still shows an error when the picture directly comes from the camera.

**Comment by zhanziyang** [comment]
> For a reason which I don't understand, it now works when choosing the files from the picture library. It still shows an error when the picture directly comes from the camera.

Does this happen on the jsfiddle demo I post (https://jsfiddle.net/jdcvpvty/6/) ?

**Comment by green-coder** [comment]
Yes, exact same behavior in the jsfiddle demo.

**Comment by green-coder** [comment]
Same behavior with the iOS 10.2.1 iPad.

**Comment by zhanziyang** [comment]
I see what is wrong. I found this: 
https://stackoverflow.com/questions/31643096/why-does-safari-throw-cors-error-when-setting-base64-data-on-a-crossorigin-an

I will fix it asap. Thank you for your feedback.

**Comment by zhanziyang** [comment]
Try this one: https://jsfiddle.net/zhanziyang/jdcvpvty/7/
If it works, then just upgrading to v0.1.4 will solve the problem.

**Comment by green-coder** [comment]
With this new version, it works on both iPad (iOS 10.2.1 and iOS 9.3.5), uploading and taking pictures.
