### ISSUE TITLE
希望用插件作为一个纯裁剪图片的功能

### ISSUE THREAD

**Issue by vivianus-chan** [zhanziyang/vue-croppa#142]
我在微信中开发，用微信jssdk自带上传组件拿到图片base64后，想手动设置initial-image然后直接进行裁剪，但是没效果，图片没显示出来，第二次同样步骤后，看到了图片是第一次设置的initial-image，想知道有没有什么办法实时更改显示剪裁区域的图片？

**Comment by zhanziyang** [comment]
记得调用`this.croppa.refresh()`.
可参考demo: https://codepen.io/zhanziyang/pen/eLQvgV?editors=1010
