### ISSUE TITLE
EXIF orientation is ignored when loaded into Croppa, wrong orientation

### ISSUE THREAD

**Issue by green-coder** [zhanziyang/vue-croppa#15]
There must be a meta-data in the image file which specifies the orientation.

**Comment by zhanziyang** [comment]
Is the image horizontally flipped? Does it happen when using back-facing camera or just front camera? As far as I know, using front-facing camera of iOS always gets a horizontally flipped image.

**Comment by green-coder** [comment]
No.

Take look at that image's EXIF: https://ibb.co/eb2x4k
(never mind that I wrote `left` and `right` at wrong places)

    Orientation	Rotate 180

Another example: https://ibb.co/iTTFqQ

    Orientation	Rotate 90 CW

When uploading **from iPad**, the orientation is wrong (probably the EXIF orientation is just ignored).

PS: The EXIF data get destroyed when you download the images from this website.

**Comment by green-coder** [comment]
I found an image for you to test. The problem happens also on computer.
https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_6.jpg

**Comment by zhanziyang** [comment]
fix in v0.2.0

[see more](https://zhanziyang.github.io/vue-croppa/#/help)

**Comment by teilzeitgeist** [comment]
I have still the same problem.
> I found an EXIF-rotated image for you to test. The problem happens also on computer.
> https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_6.jpg
> MD5: e0cac2d0a9c4f160517ec455e0f1f89c
The mentioned image is a good example for the test.

The orientation in the croppa data is correct but the shown image is wrong. When I just set the orientation to "1" than it works:

```
let meta = this.croppa.getMetadata();
test.orientation = 1;
this.croppa..applyMetadata(meta);
```

Any ideas? @zhanziyang

**Comment by tobyj** [comment]
Same happens to me with photos taken on Android phone. Orientation gets picked up and set (as seen in this.croppa.orientation = 6 for example) but it's wrong. Setting to 1 fixes it.

@Psyphant fix above works, just had typo:

```
let meta = this.croppa.getMetadata();
meta.orientation = 1;
this.croppa.applyMetadata(meta);
```
