### ISSUE TITLE
上传GIF 出来的图片是静态的 要求是动态的

### ISSUE THREAD

**Issue by w19871029** [zhanziyang/vue-croppa#157]
如果上传GIF 不想做裁切 直接上传可以吗 怎么操作 用 @file-choose="handleCroppaFileChoose" 这个拿到的file 没有那种 base64 或者blob 要求上传出来的图片是动态的 GIF

**Comment by zhanziyang** [comment]
拿到的 file 跟 blob 用法是一样的。除了`file-choose`事件，还可以用`croppa.getChosenFile()`取得

**Comment by w19871029** [comment]
有时候我想跳过裁剪 直接原图上传 应该走用哪个方法能获取到原图的的信息 可以直接上传的那种

**Comment by w19871029** [comment]
嗯 明白了
