### ISSUE TITLE
Any tricks to get this to work in WeChat's browser?

### ISSUE THREAD

**Issue by grantholle** [zhanziyang/vue-croppa#159]
I'm using `v1.3.8` and trying to get this to work inside WeChat's Android browser. iOS works totally as expected.

On my OnePlus it just does nothing, but my friends phone gave an interesting error.

没有应用可执行

Are there any tricks to get this work? I know it's not an issue with this library, but something WeChat is doing on their end to strip functionality. Any pointers would be helpful

**Comment by grantholle** [comment]
It also works fine in 微信开发者工具

**Comment by zhanziyang** [comment]
May be the same issue: https://github.com/zhanziyang/vue-croppa/issues/20

**Comment by grantholle** [comment]
Yes, that's it! Changing the `accept` option to `accept="image/*"` worked great. Thanks
