### ISSUE TITLE
Accept multiple image types

### ISSUE THREAD

**Issue by alucidwolf** [zhanziyang/vue-croppa#160]
I see in the docs you can pass in a value to the accept prop `accept="image/png"`, but I am wondering if you can pass in an array or object to indicate multiple file extensions to accept, say like both jpeg and png, but restrict everything else(gifs, svgs, etc.).

**Comment by zhanziyang** [comment]
Yes you can. Like this:
`accept="image/png, image/jpeg"`

**Comment by alucidwolf** [comment]
Thank you, was overthinking it. ^_^

**Comment by alucidwolf** [comment]
I tried that and it didn't work :(

https://codepen.io/alucidwolf/pen/KbEdLw?editors=1010

**Comment by alucidwolf** [comment]
got it

`accept=".jpg, .png"`
