### ISSUE TITLE
Vue-Croppa to ASP.Net Core causing width and height to be 500x500

### ISSUE THREAD

**Issue by UncountedBrute2** [zhanziyang/vue-croppa#165]
I have a Vue-Croppa instance that is running this: `this.$refs.cropperImage.generateDataUrl(imageInformation.type, 1)`
With width and height set to 250x250. On the asp.net side, it is being decoded as 500x500.
What's strange, is when I change the width and height of Vue-Croppa to 125x125 and Asp.Net sees it as 250x250.

Any ideas what is going on?

**Comment by zhanziyang** [comment]
yeah, the `quality` prop is set to `2` by default, so the output dimension will be 2 times larger. This is for better display on retina screen. You can set it to `1` if you don't want this.

**Comment by UncountedBrute2** [comment]
Yep, that's got it. Thanks
