### ISSUE TITLE
Would you accept a PR to make a public version of: `_onNewFileIn`

### ISSUE THREAD

**Issue by webnoob** [zhanziyang/vue-croppa#175]
I'm currently accepting pasted data from the user and this gives me access to a `File()` which `_onNewFileIn` accepts. I have my code working by calling `this.myCroppa._onNewFileIn(this.pasteFile)` but given it's an underscore I understand you meant for that to be private.

Can I expose it with a PR?

**Comment by nothingismagick** [comment]
We're working on a project that really needs this.

**Comment by zhanziyang** [comment]
Yes, please

**Comment by webnoob** [comment]
Excellent, thanks. I'll get on this later today.

Any preference to the name i,e `setFile`?

**Comment by zhanziyang** [comment]
That'll do.
