### ISSUE TITLE
How to make multiple uploads with croppa?

### ISSUE THREAD

**Issue by zefexdeveloper** [zhanziyang/vue-croppa#178]
I was wondering: I want to allow the user to select an image, crop and resize and select, after that be able to keep doing that, like this:

![image](https://user-images.githubusercontent.com/30276092/54879976-86427b00-4e1e-11e9-8cc3-fb39d569d682.png)

How can I do something similar with croppa?

**Comment by zefexdeveloper** [comment]
Is there anyone to help me with that?

**Comment by theprobugmaker** [comment]
@zhanziyang

**Comment by malesandro** [comment]
Hi! Sorry for hijacking, but did you ever worked this out?

**Comment by theprobugmaker** [comment]
@malesandro No, not yet, sorry, the repository seems abandoned.
