### ISSUE TITLE
Is possible get initial image from storage.googleapis?

### ISSUE THREAD

**Issue by yagoml** [zhanziyang/vue-croppa#196]
I'm getting CORS error ( #12 ) when i try set initial image from **storage.googleapis**, where it sure doesn't have **Access-Control-Allow-Origin** set to *.

`<img slot="initial" crossOrigin="anonymous" :src="initialImg" />`

If i remove the **crossOrigin="anonymous"** from this img tag, initial image from google storage load successfully, but i get the error #102 when i try upload images.

Any suggestion or fix?

**Comment by Kou0402** [comment]
It is easy to change the CORS settings on the Google Storage side.
Details can be found in the following documents:
・https://firebase.google.com/docs/storage/web/download-files?hl=en
