### ISSUE TITLE
Enhancement - need $emit when user closes image

### ISSUE THREAD

**Issue by hawkeye64** [zhanziyang/vue-croppa#2]
If you want to keep a "dirty" flag, which gets set to true when the User does a Zoom or Move this is easily accomplished. But, if the User closes the image with (X) then there is no signal emitted to know the image is gone.

**Comment by zhanziyang** [comment]
Update to the latest version (0.0.18) and now there's an `image-remove` event. 
Thank you for your advice!

**Comment by hawkeye64** [comment]
Thank you! Works great! I can now use this to set to a default avatar if there is no image when they save.
