### ISSUE TITLE
安卓移动端执行“@click="croppa.chooseFile()"或上传图片时会出现“没有应用程序可执行操作”导致无法选择图片

### ISSUE THREAD

**Issue by Lisi13613787118** [zhanziyang/vue-croppa#20]

**Comment by zhanziyang** [comment]
是在微信内置浏览器里的吧？其他浏览器会吗？微信屏蔽了原生的照片选择，要调用微信JS-SDK中相应的方法：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115

**Comment by Lisi13613787118** [comment]
没错，是微信内置浏览器，求大神赶紧更新，我已经写在项目里了

**Comment by zhanziyang** [comment]
请试试设置[`accept`](https://github.com/zhanziyang/vue-croppa#accept)为mimetype形式（如下），默认值的格式有一些浏览器不支持，下个版本改进。
```html
<croppa accept="image/*"></croppa>
```

**Comment by Lisi13613787118** [comment]
试了一下  安卓低端机图片可以选择 但是显示不出来  ，好点的安卓 比如小米 三星  可以选择也能编辑 ，但调用旋转或缩放时非常卡顿

**Comment by zhanziyang** [comment]
> 安卓低端机图片可以选择 但是显示不出来 

请提供一下安卓版本，如果console有报错信息，也麻烦帖一下。另外，调用一下[`supportDetection()`](https://github.com/zhanziyang/vue-croppa/blob/master/README.md#mycroppasupportdetection)并贴出返回结果。

> 调用旋转或缩放时非常卡顿

旋转卡顿与图片大小和设备性能有关，这个暂时无法解决哦；
缩放的话，你指的是调用方法（`zoomIn()`, `zoomOut()`）进行缩放吗？如果是调用方法，每调用一次都只是缩放一步，所以会有卡顿的感觉。建议用手势进行缩放，PC端用滚动，或者自行实现循环调用以达到每次缩放多步（像这样：https://codepen.io/zhanziyang/pen/EvXjXx）。

**Comment by Lisi13613787118** [comment]
安卓4.4.4 没有报错，不好意思，可以显示了，是载入慢的原因，  旋转卡顿问题确实是我的设备太差了
