### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by fortael** [zhanziyang/vue-croppa#21]
Is that possible to do not delete image when you changing background color? Would be great to have this option. Or for this better to work directly with canvas?

**Comment by zhanziyang** [comment]
Fixed in v0.2.1. Please upgrade :)

**Comment by fortael** [comment]
@zhanziyang Seems that i use latest version. When i change `canvas-color` i have to choose picture again. Or is there another way?

**Comment by zhanziyang** [comment]
You can try test here: https://zhanziyang.github.io/vue-croppa/#/customization?sec=appearance
You don't have to choose picture again after changing `canvas-color`.

**Comment by fortael** [comment]
@zhanziyang Oh, i'm sorry. My bad. Everything is working fine, you're a hero 😊

**Comment by zhanziyang** [comment]
Glad it helps. Cheers!
