### ISSUE TITLE
NPM Installation Error

### ISSUE THREAD

**Issue by dwyer14** [zhanziyang/vue-croppa#22]
When trying to install w/ NPM, getting a "Cannot read property '0' of undefined" error. Here's the log:

`999 info lifecycle undefined~uninstall: undefined
1000 verbose unlock done using ....\_locks\staging-29c759a10f8835f9.lock for D:\xampp\htdocs\one\node_modules\.staging
1001 verbose stack TypeError: Cannot read property '0' of undefined
1001 verbose stack     at rmStuff (....\npm\lib\unbuild.js:61:24)
1001 verbose stack     at tryCatcher (....\npm\node_modules\bluebird\js\release\util.js:16:23)
1001 verbose stack     at ret (eval at makeNodePromisifiedEval (....\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
1001 verbose stack     at lifecycle.then.then (....\npm\lib\install\action\unbuild.js:12:12)
1001 verbose stack     at tryCatcher (....\npm\node_modules\bluebird\js\release\util.js:16:23)
1001 verbose stack     at Promise._settlePromiseFromHandler (....\npm\node_modules\bluebird\js\release\promise.js:512:31)
1001 verbose stack     at Promise._settlePromise (....\npm\node_modules\bluebird\js\release\promise.js:569:18)
1001 verbose stack     at Promise._settlePromise0 (....\npm\node_modules\bluebird\js\release\promise.js:614:10)
1001 verbose stack     at Promise._settlePromises (....\npm\node_modules\bluebird\js\release\promise.js:693:18)
1001 verbose stack     at Async._drainQueue (....\npm\node_modules\bluebird\js\release\async.js:133:16)
1001 verbose stack     at Async._drainQueues (....\npm\node_modules\bluebird\js\release\async.js:143:10)
1001 verbose stack     at Immediate.Async.drainQueues (....\npm\node_modules\bluebird\js\release\async.js:17:14)
1001 verbose stack     at runCallback (timers.js:651:20)
1001 verbose stack     at tryOnImmediate (timers.js:624:5)
1001 verbose stack     at processImmediate [as _immediateCallback] (timers.js:596:5)`

**Comment by zhanziyang** [comment]
It seems the file `package-lock.json` caused this problem. I removed it from the repo. Please try reinstalling vue-croppa. I can't test it because I don't see this error.
```
npm uninstall --save vue-croppa
```
```
npm install --save vue-croppa
```

**Comment by dwyer14** [comment]
That might have done it...could have also been something local, though. Nuked my node_modules and that seems to have fixed it. Thanks for your help!
