### ISSUE TITLE
Wrong Image orientation on mobile (iOS)

### ISSUE THREAD

**Issue by dom-velloso** [zhanziyang/vue-croppa#229]
Hello, @zhanziyang 
Thanks for this awesome project.
Recently all mobile uploads (by taking photo) are being rotated and displaying the wrong image orientation.

Here’s an example using vue-croppa’s own Demo website:

![CF05C1A1-8ED4-43A2-B815-22D5FEF7BF8F](https://user-images.githubusercontent.com/59833288/85419714-cb38ee00-b548-11ea-8180-3cc329b0beb7.png)

**Comment by micardona96** [comment]
Adds a modifier that validates when loading the image if the orientation is equal to 6, in which case rotates the image -90 degrees, using the help **@new-image-drawn**

``` js
someMethod(){
   if (this.croppa.orientation === 6) {
          this.croppa.rotate(-1);
        }
}
```

**Comment by dom-velloso** [comment]
Thanks, @micardona96! That's what I figured :)
Cheers.
