### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by funkysoul** [zhanziyang/vue-croppa#23]
I was wondering how would you handle multiple croppa instances.
My case: I have 3-4 croppa instances each nested in a tab component, when in the final step, I would like to crop & upload all images from the single tabs. 

btw.. I love croppa!! :-)

**Comment by zhanziyang** [comment]
You can do this by binding different data keys on them. In the doc, "myCroppa" is just an example.
```html
<croppa v-model="c1"></croppa>
<croppa v-model="c2"></croppa>
<croppa v-model="c3"></croppa>
```

```js
new Vue({
  data: {
    c1: {},
    c2: {},
    c3: {}
  }
})
```

Is this what you mean to achieve?

**Comment by funkysoul** [comment]
Yeh actually that works as well.. ;-)
As I'm creating them dynamically, I've went this path:

`<croppa v-model="croppa[key]"`

`for ( var key in this.croppa ){
              if(this.croppa.hasOwnProperty(key)){
                  this.croppa[key].generateBlob((blob)=>{
                      var url = URL.createObjectURL(blob);
                      console.log(url);
                  });
              }
          }`

Thanks for your quick input :-) 
"case closed" ;-)
