### ISSUE TITLE
Ability to manually get and set the X/Y position and zoom of initial image

### ISSUE THREAD

**Issue by chrisnetonline** [zhanziyang/vue-croppa#24]
I would like the ability to get the X/Y position and zoom that resulted in the cropped image when saving to the server so that if the user wants to edit the image again I can preload the original image (which I save) as the initial image with those same values so they can pan and zoom again without having to upload the original again.

**Comment by zhanziyang** [comment]
Thank you for your feedback. It's a good suggestion!

The feature is added in the latest version (v0.3.1). See more in the [release page](https://github.com/zhanziyang/vue-croppa/releases/tag/v0.3.1).

**Comment by chrisnetonline** [comment]
Thank you for the quick turn around!

**Comment by chrisnetonline** [comment]
I need to apply the metadata as soon as the initial-image is loaded. How would I go about doing that?

**Comment by zhanziyang** [comment]
@chrisnetonline PR is merged and applied in the new release (v0.3.2).

Looks like the problem is solved so I'll close this. Please feel free to reopen it : )
