### ISSUE TITLE
Use range slider input to set zoom

### ISSUE THREAD

**Issue by chasegiunta** [zhanziyang/vue-croppa#28]
First of all, thank you for this plugin! It's a great solution our needs. Your hard work is appreciated.

I'm trying to figure out if there's a way to use a range slider input for setting the zoom/scaleRatio .

It would have to bind to the `scaleRatio` property, but not sure if croppa supports this right now, or if there's possibly a hacky way to do it via the `zoomIn()` & `zoomOut()` methods.

**Comment by zhanziyang** [comment]
It's better to use [`applyMetadata()`](https://github.com/zhanziyang/vue-croppa#applymetadatametadata) now to set scale.

I made a demo: https://codepen.io/zhanziyang/pen/eGpWRd

**Comment by chasegiunta** [comment]
Interesting. Looks like the caveats are it's not quite as smooth, nor does it continue to allow scrolling to zoom, but it gets the job done. Thanks!

**Comment by zhanziyang** [comment]
> nor does it continue to allow scrolling to zoom

@chasegiunta It is because I set `disable-scroll-to-zoom` haha. 

> it's not quite as smooth

Yes, when put large images, it is not very smooth, but small images works fine. Try decreasing the `step` property of the range slider. The smaller the step is, the smoother the zooming gets.

**Comment by zhanziyang** [comment]
@chasegiunta I updated the [demo](https://codepen.io/zhanziyang/pen/eGpWRd) using the new version of vue-croppa (v1.0.0). Now we can directly change the `scaleRatio` and large files are just as smooth.

Make sure you read the [change log]() before upgrading to this version.
