### ISSUE TITLE
Question - drag and drop an image

### ISSUE THREAD

**Issue by hawkeye64** [zhanziyang/vue-croppa#3]
Do you have plans to add support for drag and drop an image?

**Comment by zhanziyang** [comment]
Yes, I'll be working on it soon. Thanks :)

**Comment by zhanziyang** [comment]
Support drag and drop now @^0.0.19

**Comment by nobaltech** [comment]
Awesome! Very quick, thanks! It works like a charm!

**Comment by hawkeye64** [comment]
Awesome! Quick response! And, works great! 5 stars!
