### ISSUE TITLE
New $emit for 'new-image-loaded'

### ISSUE THREAD

**Issue by mattcroftuk** [zhanziyang/vue-croppa#30]
Is it possible to get a new $emit for when a new image is loaded onto the canvas?

The issue i am having is the 'new-image' event gets fired before the file is read so i am unable to get the blob of the image on a new image load manually as i wish to save the image in its original input state on adding to the canvas.

**Comment by zhanziyang** [comment]
Yes. I just realize the description about "new-image" event in the doc is not correct. Thank you for reporting this. When "new-image" is fired, the image has not yet been drawn on the canvas.

As for now you can use the "draw" event but with a little hack. The "draw" event will be fired when image is drawn for the first time and every time the state changes. So you need to set a flag to check whether it is the first "draw" event.

Here is a demo: https://codepen.io/zhanziyang/pen/zEKvbd?editors=1010

**Comment by mattcroftuk** [comment]
Yea thanks, thats the way i went after posting the issue, just thought maybe would be a nice to have.

Thanks for you help.

**Comment by zhanziyang** [comment]
@mattcroftuk 
`new-image-drawn` event is added in the newly released version v1.0.0. 
I updated the demo: https://codepen.io/zhanziyang/pen/zEKvbd?editors=1010

Make sure you read the [change log]() before upgrading to this version.
