### ISSUE TITLE
Laravel save image

### ISSUE THREAD

**Issue by majweb** [zhanziyang/vue-croppa#31]
var app = new Vue({
    el: '#app',
    data: {
        croppa: {}
    },
    methods: {
        upload() {
            if (!this.croppa.hasImage()) {
                alert('no image to upload')
                return
            }
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            this.croppa.generateBlob((blob) => {
                var fd = new FormData()
                fd.append('file', blob)
            $.ajax({
                url: '/test',
                data: fd,
                type: 'POST',
                processData: false,
                contentType: false,
                success: function(data) {
                    console.log(data)
                }
            })
        });
        }
    }
});

I have method:

public function postImage(Request $request) {
        $data = Input::get('file');
        $base64_str = substr($data, strpos($data, ",")+1);
        $image = base64_decode($base64_str);
        $imagename = uniqid('przyrzad_').'.jpg';
        file_put_contents(storage_path().'/app/public/'.$imagename, $image);
    }

Why save me emty file with correct imagename?

**Comment by zhanziyang** [comment]
I don't really know PHP but it seems you are trying to decode a base64 string. You should use [`generateDataUrl()`](https://github.com/zhanziyang/vue-croppa#generatedataurl-type-string-compressionrate-number-) if you want to get the base64 string, instead of `generateBlob()` which will return a binary file. 
And by the way, in this case you don't need to use FormData api. Just send it as a string field.

```javascript
var base64str = this.croppa.generateDataUrl()

$.ajax({
  url: '/test',
  data: {
    file: base64str
  },
  type: 'POST',
  success: function(data) {
    console.log(data)
  }
})
```

**Comment by zhanziyang** [comment]
Any progress? @majweb

**Comment by chrisnetonline** [comment]
@majweb I have this working in Laravel by doing the following:

```php
public function postImage(Request $request)
{
    if (! $request->hasFile('file') || ! $request->file('file')->isValid()) {
        return response()->json([
            'success' => false
        ]);
    }

    $request->file('file')->storeAs('users/photo/cropped', 'somefile.jpg', [
        'disk' => 'public',
        'visibility' => 'public'
    ]);

    return response()->json([
        'success' => true
    ]);
}
```
