### ISSUE TITLE
Placeholder image taints the canvas [CORS]

### ISSUE THREAD

**Issue by Linzdigr** [zhanziyang/vue-croppa#33]
Is there a way to load a placeholder image from another origin without being blocked by the security browser policy.
Indeed, it blocks the usage of exporting canvas method like `toBlob()` by tainting the canvas.

`:initial-image` is not the expected behavior here as it really loads the image and isn't the best thing for user experience.

I guess it's a request enhancement?

Thanks!

**Comment by zhanziyang** [comment]
@Linzdigr Adding `crossorigin="anonymous"` on the <img> tag can solve this problem. 
Note that **it should be written before `src`**

For example:

```html
<croppa v-model="myCroppa">
  <img slot="placeholder" crossorigin="anonymous" src="https://i.imgur.com/t4Gp9AT.jpg" class="addon">
</croppa>
```

**Comment by Linzdigr** [comment]
Indeed, it solved this issue. Thanks!
