### ISSUE TITLE
Console log with exclamation marks?

### ISSUE THREAD

**Issue by andeersg** [zhanziyang/vue-croppa#34]
Why is this present: https://github.com/zhanziyang/vue-croppa/blob/1e464541b2a2f8eb5371620e14d104f80251dabe/src/cropper.vue#L206

For me it makes no sense to have it in here.

**Comment by zhanziyang** [comment]
Fixed in v1.0.3. Thanks!

**Comment by andeersg** [comment]
Awesome, really cool plugin btw. The best one I have found for handling images.
