### ISSUE TITLE
File Input

### ISSUE THREAD

**Issue by gguney** [zhanziyang/vue-croppa#35]
I'm trying to get the image that I edited with vue-croppa. I can get Base64 but can't set it to "<input type='file'" input so that I can get it at backend which is Laravel.

I can successfully get dataUrl yet I couldn't find a way to get the edited image as a file input. Is there a way to do it with Vue-Croppa?

**Comment by zhanziyang** [comment]
Actually there is a hidden `<input type="file">`. You can find it if you use the devtool to inspect element.

But what it holds is the original file not the edited one.

To upload the edited file to backend server, you need vue-croppa to generate the blob, which is the binary file. Then using FormData api and Ajax to upload to server.
Here is a demo https://codepen.io/zhanziyang/pen/mMweXa?editors=1010

You might need to check out what FormData API is: https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

**Comment by gguney** [comment]
I saw the input yet that isn't what I wanted. I need to edit and upload up to 8 images and their path will be stored in related table. This is like you have products and their images. I don't want to upload images in first place because user can change images again and again. However, I can can upload an store images in temp folder and table.

Is there a better way to do it or generate the image file with vue-croppa?

**Comment by zhanziyang** [comment]
Have you tried using `croppa.generateBlob()` with FormData and then send it with Ajax? I think that will meet your need. It will send the edited file to server.

**Comment by gguney** [comment]
Yes, I tried it and it works for simple example however if Vue-croppa has that option it would be great, In my case there are multiple edited images and they are child nodes not the main record in DB so that means every edit for an image there will be one request to server. It makes the process more painful yet thanks for your answer.
