### ISSUE TITLE
croppa.applyMetadata() does nothing when called from inside @initial-image-loaded

### ISSUE THREAD

**Issue by huge-clewis** [zhanziyang/vue-croppa#36]
This worked in version 0.3.2 but does not work in version 1.0.3.

**Comment by zhanziyang** [comment]
Fixed in v1.0.4.

**Comment by benmann** [comment]
Literally just ran into this and the fix came out ~30 mins later.
@zhanziyang Thanks for the great component ❤️👌

**Comment by chrisnetonline** [comment]
Works perfect. Thank you!
