### ISSUE TITLE
dynamic dimensions

### ISSUE THREAD

**Issue by funkysoul** [zhanziyang/vue-croppa#37]
any recommendation on how to go regarding dynamic sizes?
Current case: 
I have croppa inside a for loop, images (remotely hosted) that are placed as initial-image can be of various dimensions.
`<v-flex v-for="(item, key, index) in item.imgfields" :key="key">
                                                <croppa v-model="croppa[key]"
                                                        :width=this.imgSize.w
                                                        :height=this.imgSize.h
                                                        :quality="2"
                                                        :file-size-limit="5502400"
                                                        :prevent-white-space="true"
                                                        accept="image/*"
                                                        @file-type-mismatch="onFileTypeMismatch"
                                                        @file-size-exceed="onFileSizeExceed"
                                                        placeholder="Drag & Drop Image here"
                                                        :placeholder-font-size="14"
                                                        :initial-image="item.image"
                                                ></croppa>
                                            </v-flex>`

So  I wrote a small method that loads the image and returns the dimensions:

`getMeta(url){
                var that = this;
                var img = new Image();
                img.addEventListener("load", function(){
                    that.imgSize.w = this.naturalWidth;
                    that.imgSize.h = this.naturalHeight;
                });
                img.src = url;
            }`

Now how can I apply the imgSize to the alredy created / rendered croppa instance?

Many thanks for your input.

**Comment by zhanziyang** [comment]
You have to bind `:width` and `:height` to different data fields if you want each instance to have different dimensions. Is it possible for your project to declare a `width` and a `height` property on each `item`? Like this:

```html
<v-flex v-for="(item, key, index) in item.imgfields" :key="key"> 
  <croppa v-model="croppa[key]"
              :width="item.width"
              :height="item.height"
              :initial-image="item.image">
    </croppa>
</v-flex>
```

For more details, check out this live demo I created according to your description: https://codepen.io/zhanziyang/pen/bojXPQ. I hope it might help~
Note that the demo is using v1.0.5, the new version fixed a few bugs.

**Comment by funkysoul** [comment]
@zhanziyang that works pretty much how I was looking for. one thing that caught my attention, when changing the source, the width and height props are not being updated

**Comment by zhanziyang** [comment]
The "source" means ... ?

**Comment by funkysoul** [comment]
@zhanziyang means when changing the initial-image property. but nevermind just at this moment I found a solution. When updating the images I just run `this.croppa.remove` and that everything get properly refreshen.

**Comment by zhanziyang** [comment]
@funkysoul you need to call `croppa.refresh()` after changing the initial image url.
