### ISSUE TITLE
Calling refresh() doesn't reset zoom

### ISSUE THREAD

**Issue by Linzdigr** [zhanziyang/vue-croppa#38]
When changing the initial image to another and calling `refresh()` doesn't reset the zoom level. I have to manually zoom out to have the full sized image (according to `prevent-white-space`).

Anyways, keep this awesome work up!

**Comment by zhanziyang** [comment]
Can you provide a demo that reproduces the issue?

It works fine here: https://codepen.io/zhanziyang/pen/LzXOYj

**Comment by Linzdigr** [comment]
Well, the real version installed was much older than 1.0.5 inspite of the correct newer version in the package.json.. Sorry for the inconvenience.
Works fine now ~
Thanks!
