### ISSUE TITLE
Manipulating stickers

### ISSUE THREAD

**Issue by emongelo** [zhanziyang/vue-croppa#39]
Hi could anyone give me some help regarding to stickers.
I have a logo that can be aligned to the right or left corner with a select input. But when a try to 'remove' the sticker with clearRect the area becomes gray and I don't know how to make it transparent.

I have this code inside `onDraw` event:

```
ctx.drawImage(
  document.querySelector(`.${sticker.class}`),
  left * this.quality,
  top * this.quality,
  sticker.width * this.quality,
  sticker.height * this.quality
 );
```

Thank you

**Comment by zhanziyang** [comment]
Hi, I hadn't thought about that, but it can be done like this (with vue-croppa@^1.0.0)
https://codepen.io/zhanziyang/pen/oGVOZp?editors=1010

Note that `croppa._draw()` is a method to force canvas to draw the image again. But it's only available in v1.0.0+. If you are using version below v1, you can add a `ref="croppa"` on croppa tag and then call `this.$refs.croppa._draw()`. 

The reason we call this method is that sticker is drawn every time the image is drawn (or updated), so we need to force the image to be drawn again after anything about sticker changes.

**Comment by emongelo** [comment]
That is exactly what I needed. Maybe you can add how to toggle stickers as example somewhere.
Thank you!

**Comment by qiuchengguang** [comment]
halo,请问你有没有想过这种截图功能可以像微信一样更换头像的时候图片位于下方，在他上方有一个半透明的框，这样就可以让用户第一时间知道这个是可以移动并且可以截图的，这个用在普遍的头像功能上面很普遍

**Comment by zhanziyang** [comment]
> halo,请问你有没有想过这种截图功能可以像微信一样更换头像的时候图片位于下方，在他上方有一个半透明的框，这样就可以让用户第一时间知道这个是可以移动并且可以截图的，这个用在普遍的头像功能上面很普遍

谢谢，这种功能的裁剪组件已经有很多了，vue-croppa只是希望提供另一种选择，不想重复造轮子。你可以搜一下，已经有很多你描述的这种开源组件了。

This conversation has nothing to do with the issue. Maybe we can open another one if you need to know more. Thanks.
