### ISSUE TITLE
Loading support

### ISSUE THREAD

**Issue by zhanziyang** [zhanziyang/vue-croppa#41]
Initially asked in the [comment](https://github.com/zhanziyang/vue-croppa/issues/40#issuecomment-339394491) of #40 .

The feature will be added in the next release (v1.1).

**Comment by zhanziyang** [comment]
v1.1.0 is out. Check the [change log](https://github.com/zhanziyang/vue-croppa/releases/tag/v1.1.0) for details.

**Comment by luiztsmelo** [comment]
Cool. Great job @zhanziyang
