### ISSUE TITLE
Using promisedBlob and reading a blob string

### ISSUE THREAD

**Issue by luiztsmelo** [zhanziyang/vue-croppa#42]
@zhanziyang I'm having trouble with the big base64 strings. It's slowing my entire website after sending the data to vuex store, so I think blob is a better solution for me. Can you write an example using promisedBlob, showing how to read the blob string generated, in a `<img>` tag? It would be interesting to put in the docs.

**Comment by zhanziyang** [comment]
@luiztsmelo Thanks. Many people have asked about the usage of blob. I will put some explanation in the docs when I have time.

Blob is not a string, it is an object that contains binary data (like a file). Usually we will upload it to server and store the file in the server, like in this example: https://codepen.io/zhanziyang/pen/mMweXa

However, you can get a `blob:` url out of a Blob object like this
```js
var url = URL.createObjectURL(blob)
// it looks like this: "blob:https://www.example.com/06668867-9000-484a-a745-9c2196e0e0bf"
```
But, unlike base64 string (usually called data url), **this `blob:` url that we create on the client side can only be used locally (on the same browser in the same session).**

I recommend you check out [this](https://stackoverflow.com/questions/20950791/html5s-file-api-blob-usages) stackoverflow page.

Conclusion:
- If you only need to display the image temporarily and locally, use `blob:` url, it's short and fast.
- If you need a permanent url, upload the Blob to server and use the server url.

A [demo](https://codepen.io/zhanziyang/pen/WXeXLo?editors=1010) using `blob:` url with `croppa.generateBlob`
A [demo](https://codepen.io/zhanziyang/pen/Zazvmw?editors=1010) using `blob:` url with `croppa.promisedBlob`

**Comment by luiztsmelo** [comment]
Thanks for explanations and hard working @zhanziyang. It's all working now.
