### ISSUE TITLE
Promise from promisedBlob method is stuck if there is no image

### ISSUE THREAD

**Issue by jpikora** [zhanziyang/vue-croppa#44]
Internally it's calling *generateBlob*, but that just returns **null** if there is no image. The callback which should eventually resolve the promise is never called in that case.

**Comment by zhanziyang** [comment]
@jpikora Yes, you are right. I will fix it. Thank you.

**Comment by zhanziyang** [comment]
It is fixed in v1.1.1. Now when there is no image, it will resolve a `null`.
