### ISSUE TITLE
如何获取图片大小(kb)，不是高宽

### ISSUE THREAD

**Issue by gavinmygit** [zhanziyang/vue-croppa#47]

**Comment by zhanziyang** [comment]
先用`generateBlob`或`promisedBlob`方法获取到 blob 对象，然后 blob.size 就是文件大小啦，不过单位是byte，需要乘以 1000 得到 kb 为单位的大小。
```js
this.croppa.generateBlob(blob => {
  if (blob) {
    console.log(blob.size * 1000);
  }
})
```
或用promise：
```js
this.croppa.promisedBlob()
.then(blob => {
  if (blob) {
    console.log(blob.size * 1000);
  }
})
```
或用 async/await 写法：
```js
var blob = await this.croppa.promisedBlob();
if (blob) {
  console.log(blob.size * 1000);
}
```

**Comment by gavinmygit** [comment]
lz，
blob.size * 1000 应该是 blob.size / 1000 得到 kb 吧？还有
 this.croppa.generateDataUrl('image/jpeg', compressionRate)图片大小为什么相差那么大啊，
e.g: 100kb的图片，按照0.5比例压缩后，上传服务器，在获取图片就成11kb了，不能按照一定比例准确控制压缩后的图片大小吗？
谢谢！

**Comment by zhanziyang** [comment]
> blob.size * 1000 应该是 blob.size / 1000 得到 kb 吧？
对对对，我说错了不好意思。

至于压缩的逻辑，其实 `generateDataUrl` 内部是直接使用原生的 [`canvas.toDataUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) 实现的，compressionRate 也是 toDataUrl() 的第二个参数，所以这个暂时控制不了

**Comment by gavinmygit** [comment]
嗯，多谢啦
