### ISSUE TITLE
promisedBlob compression seems not working properly

### ISSUE THREAD

**Issue by luiztsmelo** [zhanziyang/vue-croppa#48]
@zhanziyang this code:
`async imageConfirmed () { const blob = await myCroppa.promisedBlob('image/jpeg', 0.01) }`
is returning a not compressed .png image. 

But this is working as expected:
`async imageConfirmed () { const blob = await myCroppa.promisedBlob('image/jpeg') }`

It's a bug?

**Comment by zhanziyang** [comment]
Yeah, it's probably a bug. Let me take a look. Thanks!

**Comment by zhanziyang** [comment]
@luiztsmelo It's fixed now in [v1.13](https://github.com/zhanziyang/vue-croppa/releases/tag/v1.1.3).

Demo for test: https://codepen.io/zhanziyang/pen/zPPZRv
