### ISSUE TITLE
Clarification on getMetadata()

### ISSUE THREAD

**Issue by dwyer14** [zhanziyang/vue-croppa#49]
Was wondering if you could clarify what, exactly, the individual metadata components mean. I'm assuming the following.
- `startX`: The first/left x-coordinate of where your crop begins, multiplied by `scale`.
- `startY`: The first/top y-coordinate of where your crop begins, multiplied by `scale`.
- `scale`: The "zoom factor", or "multiplier", revealing how far you've zoomed in from your `initial-image`.
- `orientation`: The rotation of the image? Not sure on this, as it isn't applicable for my project.
I'm mostly curious about the `scale` functionality. My Croppa uses `prevent-white-space` so, as I understand it, `scale` should never be lower than 1, as you can't zoom out beyond the original/filled ratio. 

I must be confused on how `scale` works...could you shed some light on that, and maybe explain the other components too? Trying to utilize these pieces to apply transformations with [Intervention's Image](https://github.com/Intervention/image) on the back-end. Thanks!

**Comment by dwyer14** [comment]
Ultimately, I'm looking to get the `startX`, `startY`, height and width...but based on the **original** image dimensions.

**Comment by dwyer14** [comment]
I ended up passing the `outputWidth` through, and divided it by the `scale` to get the "cropped width" of the original image.

**Comment by zhanziyang** [comment]
Ok, I can understand your confusion. It's hard to explain but I'll try.

First, you need to understand the `quality` prop. The main component inside croppa is a canvas. The canvas's coordinate system is determined by its `height` and `width` properties. In croppa they are actually croppa's dimension * `quality`. `quality`'s default value is `2`, so if your croppa is 300 * 300, then by default the canvas inside is actually 600 * 600, but it's scaled to 300 * 300 with css width and height. 

- `startX` & `startY`: Think of the top-left corner of croppa container as the origin, `startX` and `startY` are the **x-coordinate and y-coordinate of the top-left corner of the source image**. Take a look at [MDN's explanation of canvas.drawImage() api](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage). `startX` and `startY` on croppa is like `dx` and `dy` on canvas, except that in croppa the canvas is scaled.
![gif](https://i.imgur.com/YR9DDtK.gif)

- `scale`: You are right that it is the "zoom factor", or "multiplier", but it's relative to the image's **natural dimension**. If the image is naturally 200 * 200, but it is 600 * 600 on the canvas, then the scale is `3`.

- `orientation`: Yes, the rotation of the image. The value is a number between 1 -8. Each number represents a type of exif orientation. Take a look at https://www.npmjs.com/package/canvas-exif-orientation

**Comment by dwyer14** [comment]
@zhanziyang Very helpful, thanks for taking the time to explain that!
