### ISSUE TITLE
Why not support IE9

### ISSUE THREAD

**Issue by WildDylan** [zhanziyang/vue-croppa#5]

**Comment by zhanziyang** [comment]
Because IE9 does not support FileReader API according to [this](http://caniuse.com/#search=filereader). This components depends on FileReader API to read files.

**Comment by WildDylan** [comment]
Terriable, Do you have some suggestions about this? we need support IE 9.

**Comment by zhanziyang** [comment]
As you know, there are two ways in which vue-croppa can read files. 
1) One is by using FileReader API to read the file the user chooses. 
2) Another one is by directly using the `<img>` element passed through ["initial" slot](https://github.com/zhanziyang/vue-croppa/blob/master/README.md#-slots). 

Now that IE 9 doesn't support FileReader, my suggestion is

Method 1: Use a FileReader polyfill. I found these: [moxie](https://github.com/moxiecode/moxie), [FileReader](https://github.com/bamarni/FileReader), [dropfile](https://github.com/MrSwitch/dropfile). I haven't tried any of them though. If they can help make FileReader api syntax work as native, then you can just go with the (1) approach.

Methad 2: If the polyfill doesn't work or you don't want to use them, then you have to use the (2) approach. You need to **somehow get the data url or remote url of the file**, apply it to the initial slot `<img>` element. And don't forget to call `refresh()` after that.
```html
<croppa v-model="myCroppa" @file-choose="onFileChoose">
  <img :src="imageUrl" slot="initial">
</croppa>
```
```js
methods: {
  onFileChoose(file) {
    var url = somehowGetTheUrlFromFile(file);
    this.imageUrl = url;
    this.myCroppa.refresh(); // don't forget to call refresh() after changing initial image
  }
}
```
Try this: [FileToDataURI](https://github.com/Aymkdn/FileToDataURI) (A cross-browser solution to read a local file and provide the base64 encoded content)

**Comment by WildDylan** [comment]
Awesome! Very thanks!

**Comment by WildDylan** [comment]
More framework needs `Flash Support`.
