### ISSUE TITLE
Persisting blob in store

### ISSUE THREAD

**Issue by luiztsmelo** [zhanziyang/vue-croppa#50]
@zhanziyang I'm using a vuex plugin that persists the session state, but the blob output doesn't persist after page refresh. It becomes an empty object. (it's the only one with this behavior). Do you know why?

**Comment by zhanziyang** [comment]
I don't understand. Technically everything inside vuex store get destroyed **after page refresh**, right?

**Comment by luiztsmelo** [comment]
Right, but I'm using this plugin: [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate). I'll try to do in another way here. Thanks
