### ISSUE TITLE
How to resolve initial image via Webpack

### ISSUE THREAD

**Issue by PrimozRome** [zhanziyang/vue-croppa#51]
I am using `vue-croppa` in Nuxt.js project which runs webpack to resolve images.

I am trying to setup initial image but it doesn't work for me. I tried:

```
<croppa initial-image="~/assets/img/profiles/1.png"></croppa>
<croppa initial-image="@/assets/img/profiles/1.png"></croppa>
<croppa initial-image="./assets/img/profiles/1.png"></croppa>
<croppa :initial-image="'./assets/img/profiles/1.png'"></croppa>
```

Any help is appreciated. Thanks.

**Comment by PrimozRome** [comment]
Never mind, found in the docs that I can supply image into `slot="initial"`

```
<croppa>
   <img src="~/assets/img/profiles/1.png" slot="initial">
</croppa>

**Comment by zhanziyang** [comment]
You need to remove the current image on croppa to drag and drop a new one.

**Comment by PrimozRome** [comment]
@zhanziyang yes I figure that our. Is there any special reason that drag and drop would not work even over image? I think it's more logical UIX case...

**Comment by zhanziyang** [comment]
@PrimozRome Um.. There is not a special reason for it. Good suggestion. I will consider implementing it in the next version. We only need to change line 848 of the src code. 

https://github.com/zhanziyang/vue-croppa/blob/e7d7f9eb27b7f9927450018355e57277fffa91c6/src/cropper.vue#L847-L850
