### ISSUE TITLE
Support replacing current image on drag and drop

### ISSUE THREAD

**Issue by zhanziyang** [zhanziyang/vue-croppa#53]
Initially asked in #51 by @PrimozRome.

**Comment by zhanziyang** [comment]
version 1.1.4 comes with a new prop: `replace-drop`
```html
<croppa replace-drop></croppa>
```

turning on `replace-drop` mode will result in current image getting replaced by the new one on drag and drop.

- type: `boolean`
- default: `false` (By default you need to remove the current image to drop a new one)

**Comment by PrimozRome** [comment]
@zhanziyang awesome, thanks for quick feature update.

**Comment by PrimozRome** [comment]
@zhanziyang I tried the 1.1.4. and added `replace-drop` but you have a bug - the drag and drop with new attribute won't work over the initial image like this:

```
<croppa
    v-model="myCroppa"
    replace-drop>
    <img src="~/assets/img/profiles/1.png" slot="initial">
</croppa>
```

With a setup like this you need to first remove the initial image and then drag and drop will work. Can you fix this in next release?

**Comment by zhanziyang** [comment]
Ok, I will look into it : )

发自我的 iPhone

在 2017年12月8日，上午1:17，Primož Rome <notifications@github.com<mailto:notifications@github.com>> 写道：


@zhanziyang<https://github.com/zhanziyang> I tried the 1.1.4. and added replace-drop but you have a bug - the drag and drop with new attribute won't work over the initial image like this:

<croppa
    v-model="myCroppa"
    replace-drop>
    <img src="~/assets/img/profiles/1.png" slot="initial">
</croppa>


With a setup like this you need to first remove the initial image and then drag and drop will work. Can you fix this in next release?

**Comment by zhanziyang** [comment]
@PrimozRome I can't reproduce your issue. I made a demo and it works fine here. Take a look. https://codepen.io/zhanziyang/pen/MONOeP

**Comment by PrimozRome** [comment]
@zhanziyang thanks. I am not using your CSS and looks like I have problem with my CSS... Thanks for your effort.
