### ISSUE TITLE
为什么使用该插件后，导出的图片大了近5倍？

### ISSUE THREAD

**Issue by 6691** [zhanziyang/vue-croppa#54]
使用插件不做任何操作，直接上传，结果图片大了近5倍。请问是什么原因？
代码：
<croppa
	id="img-canvas"
	:width="320"
	:height="320"
	v-model="myCroppa"				
	:initial-image="http://localhost:9999/static/image/640_640/8.jpg"
>
</croppa>

var _this = this;				
var _base64 = _this.myCroppa.generateDataUrl();
_this.$http.post("http://localhost/TB/upload",{
     base64:_base64,
 }).then();

原图69.7k，不做任何操作，获得base64上传成功后大小变成 342k。

**Comment by zhanziyang** [comment]
因为默认导出的是png格式，而且没有任何压缩。你可能需要用到`generateDataUrl()`方法的两个参数，详情可见文档。
