### ISSUE TITLE
canvas尺寸与container尺寸难以匹配

### ISSUE THREAD

**Issue by dc3671** [zhanziyang/vue-croppa#55]
一个常见的需求是container的width是100%窗口大小（移动端），但是canvas的大小似乎只能写固定数值？这就导致会出现以下情况，placeholder显示会错位，同时上传的图片显示也会只有一部分
![image](https://user-images.githubusercontent.com/5948851/33815480-54a0afb0-ddf7-11e7-884c-bfb80100c054.png)

**Comment by zhanziyang** [comment]
不建议在CSS中修改`.croppa-container`的`width`。

如果要动态地设置宽度，很抱歉目前只能通过JS控制——即把宽度和高度以props的形式传入(`:width`和`:height`)。如果需要动态的适应不同大小的窗口，你可以用JS获取到窗口宽度，再把计算后的值传入croppa。


```html
<croppa :width="croppaWidth" :height="croppaHeight"></croppa>
```

```js
{
  data() {
    return {
      croppaWidth: 0,
      croppaHeight: 0
    }
  },

  mounted() {
    this.croppaWidth = window.innerWidth;
    this.croppaHeigth = window.innerWidth * 2; // 假设高度是宽度的两倍
  }
}
```

**Comment by dc3671** [comment]
明白，多谢～
