### ISSUE TITLE
@file-type-mismatch doesn't emit

### ISSUE THREAD

**Issue by JKHeadley** [zhanziyang/vue-croppa#56]
Hello, first of all, great project!  I am trying to handle the "file-type-mismatch" event, however it doesn't seem to be emitting when a file of the wrong type is loaded with drag-and-drop.  It seems to be happening with the demo as well.

**Comment by zhanziyang** [comment]
I'm kinda busy right now. will look into later. Thanks.

**Comment by zhanziyang** [comment]
Fixed in [v1.1.5](https://github.com/zhanziyang/vue-croppa/releases/tag/v1.1.5).

**Comment by JKHeadley** [comment]
Thanks!
