### ISSUE TITLE
Can't direct import, have to use component?

### ISSUE THREAD

**Issue by leopsidom** [zhanziyang/vue-croppa#57]
I installed it using npm:

`npm install --save vue-croppa`

But when I use it like as I normally do:

```
import Croppa from 'vue-croppa'
export default {
  components: {
    Croppa
  }
}
```

I get error:

> [Vue warn]: Failed to mount component: template or render function not defined.

Instead I have to do this:

```
import Croppa from 'vue-croppa'
export default {
  components: {
    Croppa.component
  }
}

```

What could be wrong?

**Comment by zhanziyang** [comment]
Yes. When you directly import from `'vue-croppa'`, you need to use it as a vue plugin. 
```js
import Vue from 'vue'
import Croppa from 'vue-croppa'

Vue.use(Croppa) 
```

For more about this, check out the [Quick Start](https://github.com/zhanziyang/vue-croppa#quick-start) part of the documentation.
