### ISSUE TITLE
Created file size too large

### ISSUE THREAD

**Issue by umerhassan82** [zhanziyang/vue-croppa#58]
I am using your library, it works fine but it generates image about 4 times bigger in size, can you please let me know if there is any configurational mistake or other thing?

Original size is about 1.9mb and cropped image is about 7.9mb with quality 10.

**Comment by zhanziyang** [comment]
Please check this first: https://zhanziyang.github.io/vue-croppa/#/help and expand the first item. It may help : )

Do you really need a 10 quality though?

**Comment by zhanziyang** [comment]
@umerhassan82  Did you solve the problem?

**Comment by umerhassan82** [comment]
Yes I solved that thank you, I got it from older issues.

**Comment by narthkings** [comment]
hello i get an error when i try to update an image after it has been compressed Error: Request failed with status code 413 (Payload Too Large) is there anything i could do?
