### ISSUE TITLE
Nuxt.js - Error: [Vue warn]: Property or method "croppa" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

### ISSUE THREAD

**Issue by feedgit** [zhanziyang/vue-croppa#59]
Hello, I use NuxtJS and get this error, any one like me?

**~/plugins/croppa.js**
```
import Vue from 'vue'

if (process.browser) {
  const Croppa = require('vue-croppa')
  Vue.use(Croppa)
}
```

**nuxt.config.js**
`{ src: '~/plugins/croppa.js', ssr: false },`

Components:

```
<croppa
     v-model="croppa"
     disable-click-to-choose
     placeholder="click button on the right :)"
     :placeholder-font-size="14">
</croppa>
<a @click="croppa.chooseFile()">upload</a>
```

Error: It's no error but when reloading Window, it get error:
`[Vue warn]: Property or method "croppa" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`

Photo:

![image](https://user-images.githubusercontent.com/19923843/34560891-54450d36-f17a-11e7-9382-dd6860bd8ccf.png)

**Comment by zhanziyang** [comment]
Have you declared the `croppa` property on the `data` option of the vue instance? Like this:
```js
{
  data() {
    return {
      croppa: {}
    }
  }
}
```

**Comment by feedgit** [comment]
@zhanziyang Yup, I have `croppa: {}` in data already. I have solution with Nuxt: use <no-ssr></no-ssr> for croppa components. But this way is not render HTML of course!
