### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by fortael** [zhanziyang/vue-croppa#6]
Really great component, thanks. But here is not possible to load component asynchronously. 

```
Vue.component('croppa ', resolve => {
    require.ensure([], function() {
        require('vue-croppa/dist/vue-croppa.css');
        resolve(require('vue-croppa'));
    });
}); 
```

I need a construction like that. But `Vue.component` already in it. Can you provide some methods to get exactly component? Like `require('vue-croppa').component`. Because here is nothing extraordinary in install script. Looking forward. Thanks

**Comment by zhanziyang** [comment]
I will look into that. Thanks!

**Comment by zhanziyang** [comment]
hey man, try this out:
```js
Vue.component('croppa ', resolve => {
    require.ensure([], function() {
        require('vue-croppa/dist/vue-croppa.css');
        resolve(require('vue-croppa/src/cropper.vue'));
    });
}); 
```
