### ISSUE TITLE
Maximum call stack size exceeded with Vue.js devtools

### ISSUE THREAD

**Issue by Maestru2a** [zhanziyang/vue-croppa#64]
I was using your library and I had a problem in the chrome devtools provided by Vuejs.
If I dont v-model any data, the following problem will not happend.

My problem : if I want to check the current data on the component where I declared Croppa (like on the next image), it will send a "maximum call stack size exceeded" in the console.
<img width="500" alt="capture d ecran 2018-01-13 a 09 55 31" src="https://user-images.githubusercontent.com/18480834/34904525-f065a97c-f847-11e7-9c7a-c1cd67972be1.png">

Here are the detail of the console error:
`Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at D (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:20139)
    at chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:18645
    at x (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:18704)
    at t.a (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:14243)
    at Object.y (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:1927)
    at e (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:5819)
    at e (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:5837)
    at e (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:5837)`

If I do a console.log inside my code, the data log correctly.
My registration is like this :
```javascript
import Croppa from "vue-croppa"
export default {
	components: {
		Croppa: Croppa.component
	},
	data: function() {
		return {
			croppa: {}
		}
	},
```
```html
<croppa v-model="croppa" :width="350" :height="350" :quality="3" initial-size="cover" initial-position="center"></croppa>
```
Amazing job on the library by the way 👍

**Comment by zhanziyang** [comment]
I will look into it when I have time. For now, maybe you can try using the `ref` instead of `v-model`.

> - Since v1.0.0, the v-modeled value and the `ref` both point to the same thing - the component itself. So you don't need to set v-model anymore if you have a `ref` on the component.
```xml
<croppa ref="myCroppa"></croppa>
```
```js
this.$refs.myCroppa.chooseFile()
this.$refs.myCroppa.generateDataUrl()
// ...
```

**Comment by mateo2181** [comment]
I had the same problem.  Using ref works fine! Thanks!

**Comment by zhanziyang** [comment]
@Maestru2a @larsboldt @mateo2181 
Guys, it seems to be a bug in the new vue-devtool: vuejs/vue-devtools#528 .
They have fixed it in the latest version. Try reinstall the chrome-extension. 
We can stay with v-model now.

**Comment by gloddo** [comment]
Hi, sorry to reopen this again, but I'm having the same issue. I don't know if it is actually related to vue-devtools, also because I'm running the lastest version as of today (5.1.1 on Chrome), but using v-model on a nested croppa gives me this error. 
What can it be?
Thank you.
