### ISSUE TITLE
支持vue2.0以上吗，谢谢!

### ISSUE THREAD

**Issue by FlyingIdeal** [zhanziyang/vue-croppa#66]
"vue-croppa": "^1.1.5", 支持>vue2.0以上吗？挂在components里面会一直提示Failed to mount component: template or render function not defined.

**Comment by FlyingIdeal** [comment]
已经解决问题，打扰了

Croppa: Croppa.component

**Comment by alicecoding** [comment]
解决了么，我刚用，也是遇到同样的问题，请问要如何解决呢
