### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by emongelo** [zhanziyang/vue-croppa#67]
I found your component pretty awesome. I could make a lot of customizations but now I don't know how to add rounded corners support. Did you try or do you know how to make it possible?

Thanks!

**Comment by zhanziyang** [comment]
Do you just want the component UI to have rounded corners or you want the output image to have rounded corners?

If it's the former, then you can achieve it easily by modifying the css style of `.croppa-container`. Apply `border-radius` to this class selector. See example [here](https://zhanziyang.github.io/vue-croppa/#/customization).

If it's the latter, maybe I will implement this feature in the next version. Good suggestion, thanks!

**Comment by emongelo** [comment]
Unfortunately, I was talking about a 'circle crop' functionality.

**Comment by zhanziyang** [comment]
Please try new version 1.2.0:
- New prop: **image-border-radius**
  Set rounded corders to image. Note that this has effect on the output image. **And it only works when `prevent-white-space` is `true`**.
  [Demo](https://codepen.io/zhanziyang/pen/jZNmOa)

**Comment by emongelo** [comment]
Awesome bro! It's exactly what I needed. It works as expected. Thank you!
