### ISSUE TITLE
Preview Image 

### ISSUE THREAD

**Issue by gguney** [zhanziyang/vue-croppa#68]
Hello ,

I would like to create a preview for Croppa. I have a page which will have preview image of VueCroppa (dynamic) and modal which will have Vue-Croppa in it so user can edit the image in modal not the page itself.

 If I try to put Vue-Croppa in modal and trigger myCroppa.chooseFile() outside the modal then Vue gives me error that myCroppa.chooseFile() is not a function since it is in the modal (modal is hidden).

 I tried to use Vue-Croppa (I have 1 myCroppa object) as preview but the other instance of vue-croppa couldn't catch the first vue-croppa's myCroppa object.  

I try to create a canvas and change its context with VueCroppa and it didn't work. 

What should I do? Should I use another component? Or Vue-Croppa can make something like that?

**Comment by zhanziyang** [comment]
> I try to put Vue-Croppa in modal

> modal is hidden 

By that, do you mean the vue-croppa component is not rendered? Have you consider using css to hide the modal, like `visibility: hidden` or `opacity: 0` so that vue-croppa will be rendered?

**Comment by gguney** [comment]
Yes I did it however since there were 2 vue-croppa component and v-model with 1 object did not work. I try to use 2 vue-croppa side by side 1. loaded the selected image yet 2. didn't do anything. (they have same object in v-model)

I wanted to make a classic preview / extended edit in modal type of image editing but I couldn't achive that. 

Do you have any idea about it ? What can I do?

Also I know it is not a bug but maybe a feature request ? vue-croppa preview component which is not editable just a simple image, preview of vue-croppa's edited image.

**Comment by zhanziyang** [comment]
Please try new version 1.2.0:
- New prop: **passive**
Switch to passive mode. Croppa in passive mode will sync state with another croppa if they `v-model` the same object. Also it will not have self-control - user can't manipulate image on passive croppa. This is useful as a preview component.

  These states will be synced:
  ```js
  ['imgData', 'img', 'imgSet', 'originalImage', 'naturalHeight', 'naturalWidth', 'orientation', 'scaleRatio']
  ```
  [Demo](https://codepen.io/zhanziyang/pen/xYKbqJ)

**Comment by chuoke** [comment]
in this way,  the previewer must be same size with main croppa, otherwise it's not  normal.
Did i miss anything?

**Comment by zhanziyang** [comment]
@chuoke Yeah, that's something that needs to be improved.

**Comment by zhanziyang** [comment]
@chuoke 
```css
.previewer canvas {
    height: 100px !important;
    width: 100px !important;
}
```
Override the canvas's css style can make the previewer have any size you want.
