### ISSUE TITLE
0.1.1 - Having canvas-color="transparent" causes the image to stay as background when removed

### ISSUE THREAD

**Issue by brunogaspar** [zhanziyang/vue-croppa#7]
When the `canvas-color="transparent"` is added to the component and when you click to remove the image, it stays as the background.

Reproducible Fiddle https://jsfiddle.net/jdcvpvty/3/

Thanks for project though :)

**Comment by zhanziyang** [comment]
Looks like a bug. I will look into it. Thanks for your feedback.

**Comment by zhanziyang** [comment]
Fixed. Please upgrade to [v0.1.3](https://unpkg.com/vue-croppa@0.1.3/dist/vue-croppa.min.js).

**Comment by brunogaspar** [comment]
Awesome, thank you!
