### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by redijedi** [zhanziyang/vue-croppa#70]
It will not load when trying to use the component from within another component.

```
  import Vue from 'vue';
  import Croppa from 'vue-croppa';
  ...
  Vue.use(Croppa);

  export default {
    ...
    components: {
      Croppa,
    },
    ...
```

**Comment by zhanziyang** [comment]
Either
```js
Vue.use(Croppa);
```
or 
```
components: {
   croppa: Croppa.component
},
```
Use one of the two methods. 

And note that when you do: 
```js
import Croppa from 'vue-croppa';
```
here `Croppa` is a **vue plugin** (that can be passed to Vue.use), not a **vue component**. `Croppa.component` is the vue component. So if you choose the second method, you should use `Croppa.component`.

**Comment by redijedi** [comment]
That works! Thanks for the quick response. Also, nice lib!

**Comment by xreyc** [comment]
> Either
> 
> ```js
> Vue.use(Croppa);
> ```
> 
> or
> 
> ```
> components: {
>    croppa: Croppa.component
> },
> ```
> 
> Use one of the two methods.
> 
> And note that when you do:
> 
> ```js
> import Croppa from 'vue-croppa';
> ```
> 
> here `Croppa` is a **vue plugin** (that can be passed to Vue.use), not a **vue component**. `Croppa.component` is the vue component. So if you choose the second method, you should use `Croppa.component`.

It works! thanks.

**Comment by jhays89** [comment]
This was helpful. Thank you =)
