### ISSUE TITLE
On resizing startX and Y reset

### ISSUE THREAD

**Issue by FraukeVdz** [zhanziyang/vue-croppa#72]
Hey 

When I change the width and height of the widget, the position of the image is reset to the middle. But when the widget is resized, I want the image to hold his original position (chosen by the user).

I can't seem to find the place in the code where this happens.

Can you help me?

Thanks!

**Comment by zhanziyang** [comment]
This is expected if you set `prevent-white-space` to `true`. 
Code is at: https://github.com/zhanziyang/vue-croppa/blob/5e661062b34063967995ee5c201c8ee8ad20c600/src/cropper.vue#L1139-L1149
As you can see, if `preventWhiteSpace` is `true`, `imageSet` will be `false`, then in the `this._placeImage() ` function, the image position will be reset.

If you are curious why it should work this way, please see more in [this issue](https://github.com/zhanziyang/vue-croppa/issues/26).
