### ISSUE TITLE
Is there any way to check if user has chosen the file?

### ISSUE THREAD

**Issue by meetzaveri** [zhanziyang/vue-croppa#75]
I thoroughly saw whole `croppa` object. But it doesn't have any boolean property like `hasChosenImage` or `hasImage` set.

 So can you guide ?

**Comment by zhanziyang** [comment]
Take a look at `imageSet`. It might be what you need.
`this.croppa.imageSet`

**Comment by meetzaveri** [comment]
@zhanziyang Will look at it !

**Comment by meetzaveri** [comment]
Yes it's working @zhanziyang !

**Comment by zhanziyang** [comment]
Great. Then I'm going to close this.
