### ISSUE TITLE
this.$refs.croppa.chooseFile() is not opening file explorer

### ISSUE THREAD

**Issue by snovakovic** [zhanziyang/vue-croppa#78]
After calling `this.$refs.croppa.chooseFile()` nothing happens. Clicking on preview windows opens explorer window. 

Enviroment: 
* Ubuntu: 16.04
* Chrome: 65
* Vue: 2.5.8

==== UPDATES =====

It's happening only if `this.$refs.croppa.chooseFile()` is called in same function call when the flag to display croppa is set to true. 

```
    test() {
      this.editPicture = true; // v-if="editPicture" is set on croppa element
      this.$nextTick().then(() => {
        setTimeout(() => { // Timeout is set just for testing same behaviour with or without it
           // NOTHING HAPPENS AT THIS POINT (BUG)
           this.$refs.croppa.chooseFile();
        }, 150);
        // Auto open file explorer
      });
    },
```

**Comment by zhanziyang** [comment]
Yes, that's normal because if v-if="false" the component is not rendered. You can use v-show="false" to hide it while still render the DOM.

**Comment by snovakovic** [comment]
Yes but I'm calling chooseFile inside of nextTick and for the test after timeout at which point the component should be rendered. So I don't see reason why it shouldn't work for example from above? I'm using v-show as a workaround but I would prefer v-if as for my uscase component will not be needed in most of the cases.

**Comment by zhanziyang** [comment]
https://codepen.io/zhanziyang/pen/JLRgLG?editors=1010
See this demo. It works fine here.

**Comment by snovakovic** [comment]
@zhanziyang indeed it is! Thanks for the demo I will do some more investigation tomorrow to see what is going on in context of my application and demo code. I will close the issue for now.
