### ISSUE TITLE
this.croppa.getChosenFile() is returning undefined on drop

### ISSUE THREAD

**Issue by lraphael** [zhanziyang/vue-croppa#81]
Hi,

I'm using the getChosenFile() for getting the original filename and that works fine for fileinput files, but isn't working for drag over files. Is there another way to detect the original filename using drag and drop?

Thanks!

**Comment by zhanziyang** [comment]
Technically `getChosenFile()` should return the file no matter how the input is done. So it's a bug. I will fix it asap.

**Comment by zhanziyang** [comment]
@lraphael For now you can use  the `file-choose` event.
```html
<croppa @file-choose="handleFileChoose"></croppa>
```
```js
{
  handleFileChoose(file) {
    console.log(file);
  }
}
```

**Comment by lraphael** [comment]
Yes, It's working smoothly!
Thanks!

**Comment by shoutershub** [comment]
i know this status is closed , but i just wanted to ask somthing, lets say i already have a button for this `croppa.chooseFile()` how do i tie it to the event?

**Comment by zhanziyang** [comment]
@shoutershub So by clicking your button will call `croppa.chooseFile()`, right? Then the event still works just like how we normally do: 
```
<croppa @file-choose="handleFileChoose"></croppa>
```

**Comment by shoutershub** [comment]
Ok, thanks that was helpful... 
Nice plugin bro.
