### ISSUE TITLE
Infinite update loop when resizing container

### ISSUE THREAD

**Issue by CookieJon** [zhanziyang/vue-croppa#83]
I have a Vue-croppa with "auto-sizing" option, placed inside a resizable container div, 

Intermittently, when resizing the container div, Croppa hangs and the following error is reported in the console:

>  You may have an infinite update loop in watcher with expression "outputWidth"

![image](https://user-images.githubusercontent.com/6636471/37809294-b90d057e-2ea2-11e8-8488-22afe9c4145e.png)

Cheers.

**Comment by zhanziyang** [comment]
Thanks for reporting. I will look into it.

**Comment by CookieJon** [comment]
No sweat. Nice component!

I've also now noticed this error in instances other than resizing as well.
I'm in transit now, but I'll try to reproduce it in a JS Fiddle for you
later.

Ta,
Jon.

**Comment by zhanziyang** [comment]
I am trying to reproduce the problem but I wonder what is the way you make the div resizable. I guess I'll wait for your JS fiddle.
