### ISSUE TITLE
hasImage() returns false even after an image is chosen

### ISSUE THREAD

**Issue by AllenTzul** [zhanziyang/vue-croppa#86]
I was trying to generate the data url for a selected image but it fails. I then looked at the croppa code and realized that hasImage() returns false even after an image is selected. I'm calling hasImage() from within the  file-choose event handler so is that a bug? I'm using vue-croppa version 1.3.0

**Comment by AllenTzul** [comment]
Never mind. I missed the new-image event that provides me with what I need. Sorry.

**Comment by zhanziyang** [comment]
Yes, hasImage() returns true when the image is actually drawn onto the canvas. `file-choose` event gets fired right after an image is chosen but not necessarily successfully read and drawn.
