### ISSUE TITLE
image-border-radius不可以设置成50%吗？

### ISSUE THREAD

**Issue by lebuslebos** [zhanziyang/vue-croppa#88]
### 求助
设置image-border-radius的值为canvas宽的一半的时候，没有变成圆形。
想设置成50%的时候发现不行。
然后自己在css里面写了：

    canvas{
        border-radius: 50%
    }

发现也不行。

**Comment by zhanziyang** [comment]
不支持百分数。圆形会稍微麻烦一点，可以看这个demo：https://codepen.io/zhanziyang/pen/GQKmJq?editors=1111

**Comment by zhanziyang** [comment]
相关issue: #67

**Comment by lebuslebos** [comment]
@zhanziyang 感谢大神！！
