### ISSUE TITLE
怎样才能点击图片的时候就可以重新选图片？

### ISSUE THREAD

**Issue by lebuslebos** [zhanziyang/vue-croppa#89]
我分别绑定了croppa自己和他的父元素的点击事件，在事件中用this.croppa的remove()和chooseFile()方法，但是都失败了。

**Comment by zhanziyang** [comment]
这个不支持，因为croppa上有图片时，鼠标是进行移动和缩放操作。有一个hack方案，看这个demo：https://codepen.io/zhanziyang/pen/vRZrox

但是用这个方案的话，move和zoom的手势就不支持了
