### ISSUE TITLE
How to define/instanciate `myCroppa`?

### ISSUE THREAD

**Issue by green-coder** [zhanziyang/vue-croppa#9]
The documentation is not clear on where myCroppa is defined and how it should be instanciated.

**Comment by zhanziyang** [comment]
It should be defined on the `data` option of the parent component. 
Here is an example:
https://jsfiddle.net/jdcvpvty/2/

**Comment by green-coder** [comment]
That's a nice example. I suggest you to add the link to the `README.md` and that you add to the paragraph https://github.com/zhanziyang/vue-croppa#v-model that the v-model the user provides can be a null object - at the moment, the wording does not make it obvious.

**Comment by zhanziyang** [comment]
Great. Thanks for your suggestion.
