### ISSUE TITLE
Can you please make it possible to extend the events?

### ISSUE THREAD

**Issue by Tsingbo-Kooboo** [zhanziyang/vue-croppa#90]
I found the code is like the following:
```vue
<canvas ref="canvas"
      @click.stop.prevent="_handleClick"
      @touchstart.stop="_handlePointerStart"
      @mousedown.stop.prevent="_handlePointerStart"
      @pointerstart.stop.prevent="_handlePointerStart"
      @touchend.stop.prevent="_handlePointerEnd"
      @touchcancel.stop.prevent="_handlePointerEnd"
      @mouseup.stop.prevent="_handlePointerEnd"
      @pointerend.stop.prevent="_handlePointerEnd"
      @pointercancel.stop.prevent="_handlePointerEnd"
      @touchmove.stop="_handlePointerMove"
      @mousemove.stop.prevent="_handlePointerMove"
      @pointermove.stop.prevent="_handlePointerMove"
      @pointerleave.stop.prevent="_handlePointerLeave"
      @DOMMouseScroll.stop="_handleWheel"
      @wheel.stop="_handleWheel"
      @mousewheel.stop="_handleWheel"></canvas>
```
And in the method for example "_handleClick", you do not emit an event, which means that developer is not easy to write some bussiness logic when the event is trigger.Can you please make it possible to extend the events?

**Comment by zhanziyang** [comment]
Yes, it'll do.

**Comment by Tsingbo-Kooboo** [comment]
Thank you very much! And may I know when you plan to make this change?

**Comment by zhanziyang** [comment]
@Tsingbo-Kooboo Please upgrade to v1.3.3 you can use native event like `@click`. Example: https://codepen.io/zhanziyang/pen/aYPoea?editors=1011

**Comment by Tsingbo-Kooboo** [comment]
@zhanziyang the event will not trigger in mobile. Steps to reproduce:

1.  open the [example](https://codepen.io/zhanziyang/pen/aYPoea?editors=1011) you write.
2.  switch to the mobile version(also you can open it in mobile directly).
3.  click the image placeholder.

you will see that the open file dialog is open but do NOT alert 'clicked'.
It works fine in desktop version.
![image](https://user-images.githubusercontent.com/4373886/38480132-42339a60-3bf6-11e8-8f80-c7eb8d75b581.png)

**Comment by zhanziyang** [comment]
@Tsingbo-Kooboo I forgot to mention you need to use `@touchstart` on mobile. Is this ok for you? I edit the demo: https://codepen.io/zhanziyang/pen/aYPoea?editors=1011
