### ISSUE TITLE
Bootstrap is-invalid with vue-croppa?

### ISSUE THREAD

**Issue by Tarasovych** [zhanziyang/vue-croppa#92]
For displaying errors near default input I used to do this:
```vue
<div class="form-group">
    <label class="col-md-8 control-label">Foo input</label>
    <input type="foo" class="form-control" v-model="foo"
         :class="{' is-invalid': errors.foo}">
    <div class="invalid-feedback" v-if="errors.foo">
         <strong v-for="value in errors.foo">{{value}}</strong>
     </div>
</div>
```
How can I achieve this for `<croppa>`? Because of there is only hidden input, rendered by `<croppa>`, I can't put ` :class="{' is-invalid': errors.foo}"` directly to that input. Thanks!

What did I do:
```vue
<div class="form-group">
    <div>
        <croppa v-model="myCroppa"
            ...
        ></croppa>
    </div>

    <div class="invalid-feedback" v-if="errors.myCroppa">
        <strong v-for="value in errors.myCroppa">{{value}}</strong>
    </div>
<div class="form-group">
```
but the div `<div class="invalid-feedback">` goes `display: none` all the time.

**Comment by zhanziyang** [comment]
So you want to add attrs on the hidden input, right?
If so, you can use `input-attrs` prop (https://github.com/zhanziyang/vue-croppa#input-attrs)
```html
<croppa :input-attrs="{class: 'is-invalid'}"></croppa>
```

**Comment by Tarasovych** [comment]
I guess, `:input-attrs="{class: 'is-invalid'}"` isn't suitable here, because Vue need computed property (`:class=""`).

**Comment by zhanziyang** [comment]
This is computed too. You can do something like `:input-attrs="{class:  errors.screenshot ? 'is-invalid' : ''}"`
