### ISSUE TITLE
clip plugin

### ISSUE THREAD

**Issue by bhritch** [zhanziyang/vue-croppa#96]
Would like to ask if i can get the square image before it transform to circle using clip plugin? is is possible?
or can i add something like overlay circle in the canvas for avatar purposes? tia

**Comment by zhanziyang** [comment]
>  if i can get the square image before it transform to circle using clip plugin?

Do you mean that what users see is square image but output is cliped? I think that's against the "what you see is what you get" principle.

> add something like overlay circle in the canvas

Do you mean something like this:
![image](https://user-images.githubusercontent.com/10041024/38843575-3d7946be-4222-11e8-9962-c59b2158103d.png)
If so, maybe you should try [vue-croppie](https://github.com/jofftiquez/vue-croppie). It has a different way for user interaction, a more traditional way that many people are familiar with.

**Comment by bhritch** [comment]
yes, something like that, but i still need to save the original image or what i need is just a overlay placeholder which is the circle. but will take a look vue-croppie
or change my approach. thanks man.

**Comment by zhanziyang** [comment]
I'm closing this. Feel free to reopen.
