### ISSUE TITLE
croppa.refresh()之后不能传和之前一样的图片

### ISSUE THREAD

**Issue by lebuslebos** [zhanziyang/vue-croppa#97]

**Comment by zhanziyang** [comment]
是的。会尽快解决！

**Comment by lebuslebos** [comment]
我在file-choose的事件里面再次手动删除图片，好像就可以了。不知道这样做有没有什么道理？
我的想法是，是不是光点删除按钮，之前的没有删干净，所以再删一次。
    
    onFileChoose(){
                this.croppa.remove();
            },

**Comment by zhanziyang** [comment]
@lebuslebos 嗯，这应该是个bug

**Comment by zhanziyang** [comment]
@lebuslebos  Fixed in v1.3.6.
